---
name: "y-job"

on:
  repository_dispatch:
    types: [ deployment-event ]
  push:
    branches:
      - main  
jobs:
    
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "y-job first step."
        run: echo "y-job"
